services:
  ruby:
    build:
      context: .
    environment:
      PGHOST: postgres
      PGPASSWORD: password
      PGUSER: user
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: activerecord-bulk_update_test
